/*
    날짜: 2023/10/05
    이름: 이지민
    실습: 5장 내부 조인(INNER JOIN)
*/
SELECT *
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT *
FROM EMP E
JOIN DEPT D
USING (DEPTNO);

SELECT *
FROM EMP E, DEPT D
WHERE e.DEPTNO = D.DEPTNO;

SELECT 
    E.EMPNO,
    E.ENAME,
    E.JOB,
    E.MGR,
    E.HIREDATE,
    E.SAL,
    E.DEPTNO,
    D.DNAME,
    D.LOC
FROM EMP E
JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE SAL <= 3000
ORDER BY E.DEPTNO, EMPNO;

-- 5-2 실습. 외부 조인 실습
SELECT * FROM EMP E1 LEFT JOIN EMP E2 ON E1.MGR = E2.EMPNO;
SELECT * FROM EMP E1 RIGHT JOIN EMP E2 ON E1.MGR = E2.EMPNO;
